# ${project.name}

${project.description}

- **Archetype:** ${archetype}
- **Language / runtime:** ${project.language} (${project.runtime}), pkg: ${project.package_manager}
- **Framework / architecture:** ${project.framework} / ${project.architecture}

<!-- >>> ack:managed (do not edit; regenerated by /ack-init) >>> -->
Contract gate: **${contract_gate.mode}** (dialect ${contract_gate.glob_dialect}). Protected paths:
#ack:each contract_gate.protected_paths as "- `$item`"

Local dev runs in containers: **`docker compose up --build`** (API + Postgres). The
image is built from `Dockerfile`; tune it as the code lands.

Child pointers (see child docs/agent config):
@.claude/conventions.md
@docs/contracts/
<!-- <<< ack:managed <<< -->

<!-- TODO(P4): DEEP backend-api CLAUDE.md content (house style, agent roster,
     per-architecture conventions) is deferred to P4. This skeleton renders a
     correct child pointer + managed gate block for the branch-matrix test. -->
