# ${project.name}

${project.description}

- **Archetype:** ${archetype}
- **Language / runtime:** ${project.language} (${project.runtime}), pkg: ${project.package_manager}
- **Framework / architecture:** ${project.framework} / ${project.architecture}

<!-- >>> ack:managed (do not edit; regenerated by /ack-init) >>> -->
Contract gate: **${contract_gate.mode}** (dialect ${contract_gate.glob_dialect}). Protected paths:
#ack:each contract_gate.protected_paths as "- `$item`"

Design system: install=${design_system.install}, source=${design_system.source}.

Child pointers (see child docs/agent config):
@.claude/conventions.md
@docs/contracts/
@design-system/
<!-- <<< ack:managed <<< -->

<!-- TODO(P4): DEEP fullstack CLAUDE.md content (web + api tiers, design-system
     usage, agent roster) is deferred to P4. This skeleton renders a correct child
     pointer + managed gate block + design-system pointer for the branch matrix. -->
