# ${project.name}

${project.description}

- **Archetype:** ${archetype} (Vercel + Next.js App Router + React + shadcn/ui + Supabase)
- **Language / runtime:** ${project.language} (${project.runtime}), pkg: ${project.package_manager}
- **Framework / architecture:** ${project.framework} / ${project.architecture}
- **Auth:** ${auth.provider} · **Hosting:** ${hosting.target} · **Billing:** ${billing.provider}
- **Persistence:** enabled=${persistence.enabled}

<!-- >>> ack:managed (do not edit; regenerated by /ack-init) >>> -->
## Intent first (specs lead, code follows)

This product's intent lives in `specs/`. Read it before writing code — the specs are
the definition of done, and the contract gate traces edits back to them.

@specs/PRD.md
@specs/ARCHITECTURE.md
@specs/REQUIREMENTS.md
@specs/PLAN.md
#ack:if design_system.install
@specs/DESIGN.md
#ack:endif

1. Before writing code, the relevant FR/NFR in `specs/REQUIREMENTS.md` and its
   acceptance criteria are your definition of done; the contract gate traces edits
   to them.
2. The build order and the first vertical slice are in `specs/PLAN.md`. Land the
   thinnest end-to-end slice first (auth → data → billing), proving the thesis.

#ack:if design_system.install
## Design system & UX
@specs/DESIGN.md
@design-system/
This product's visual + UX intent lives in `specs/DESIGN.md` (brand, key screens,
density, a11y target, design acceptance DA-NN). The tokens are materialized in
`design-system/theme/` from `design_system.tokens` — never introduce ad-hoc colors,
spacing, or components outside the system. shadcn/ui components are copied into
`components/ui/` (you own them). Honor the `brand-guidelines` /
`frontend-design-guidelines` / `shadcn-ui` skills for HOW to apply them. Design "done"
is the DA-NN criteria (focus-visible on every component, tokens-not-magic-numbers,
WCAG AA verified) and, where a design path is protected, traces to a contract.
#ack:endif

## Stack (always present in this archetype)

- **Auth via ${auth.provider}**: `lib/auth.ts` + `middleware.ts`. Clerk middleware
  protects the `/dashboard` route group; marketing routes stay public.
- **Billing via ${billing.provider}**: `app/api/billing/checkout/route.ts` (create a
  Checkout Session) + `app/api/billing/webhook/route.ts` (verify + handle events).
#ack:if persistence.enabled
- **Data via ${persistence.db} / ${persistence.orm}**: client + schema under `lib/db/` and `db/`.
#ack:endif
- **Containers**: local dev is **`docker compose up --build`** (app + Postgres); the
  production image is built from `Dockerfile` (Next.js standalone). Prod targets
  ${hosting.target}; the compose Postgres is for local dev only.

## Contract gate
Contract gate: **${contract_gate.mode}** (dialect ${contract_gate.glob_dialect}). Protected paths:
#ack:each contract_gate.protected_paths as "- `$item`"

Design system: install=${design_system.install}.

#ack:if features.iac
## Infrastructure as Code
This project provisions infrastructure with **${iac.tool}** targeting **${iac.provider}**.
The IaC scaffold lives in `infra/`. Treat `infra/**` as a protected surface: changes go
through a contract and the usual review.
#ack:endif

Child pointers (see child docs/agent config):
@.claude/conventions.md
@docs/contracts/
@design-system/
<!-- <<< ack:managed <<< -->
